# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aoe_interpolator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='aoe_interpolator.proto',
  package='aoeinterpolator',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16\x61oe_interpolator.proto\x12\x0f\x61oeinterpolator\"<\n\x13StartPyTorchRequest\x12\x11\n\tallowCuda\x18\x01 \x01(\x08\x12\x12\n\nnumThreads\x18\x02 \x01(\x05\"8\n\x14StartPyTorchResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"I\n\x18InterpolatedFrameRequest\x12\x0e\n\x06\x66rame1\x18\x01 \x01(\x0c\x12\x0e\n\x06\x66rame2\x18\x02 \x01(\x0c\x12\r\n\x05\x61lpha\x18\x03 \x01(\x02\"*\n\x19InterpolatedFrameResponse\x12\r\n\x05\x66rame\x18\x01 \x01(\x0c\"\x14\n\x12StopPyTorchRequest\"7\n\x13StopPyTorchResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xbd\x02\n\x0f\x41oeInterpolator\x12]\n\x0cStartPyTorch\x12$.aoeinterpolator.StartPyTorchRequest\x1a%.aoeinterpolator.StartPyTorchResponse\"\x00\x12o\n\x14GetInterpolatedFrame\x12).aoeinterpolator.InterpolatedFrameRequest\x1a*.aoeinterpolator.InterpolatedFrameResponse\"\x00\x12Z\n\x0bStopPyTorch\x12#.aoeinterpolator.StopPyTorchRequest\x1a$.aoeinterpolator.StopPyTorchResponse\"\x00\x62\x06proto3')
)




_STARTPYTORCHREQUEST = _descriptor.Descriptor(
  name='StartPyTorchRequest',
  full_name='aoeinterpolator.StartPyTorchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='allowCuda', full_name='aoeinterpolator.StartPyTorchRequest.allowCuda', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='numThreads', full_name='aoeinterpolator.StartPyTorchRequest.numThreads', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=103,
)


_STARTPYTORCHRESPONSE = _descriptor.Descriptor(
  name='StartPyTorchResponse',
  full_name='aoeinterpolator.StartPyTorchResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='aoeinterpolator.StartPyTorchResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='aoeinterpolator.StartPyTorchResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=161,
)


_INTERPOLATEDFRAMEREQUEST = _descriptor.Descriptor(
  name='InterpolatedFrameRequest',
  full_name='aoeinterpolator.InterpolatedFrameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame1', full_name='aoeinterpolator.InterpolatedFrameRequest.frame1', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame2', full_name='aoeinterpolator.InterpolatedFrameRequest.frame2', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alpha', full_name='aoeinterpolator.InterpolatedFrameRequest.alpha', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=236,
)


_INTERPOLATEDFRAMERESPONSE = _descriptor.Descriptor(
  name='InterpolatedFrameResponse',
  full_name='aoeinterpolator.InterpolatedFrameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame', full_name='aoeinterpolator.InterpolatedFrameResponse.frame', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=280,
)


_STOPPYTORCHREQUEST = _descriptor.Descriptor(
  name='StopPyTorchRequest',
  full_name='aoeinterpolator.StopPyTorchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=302,
)


_STOPPYTORCHRESPONSE = _descriptor.Descriptor(
  name='StopPyTorchResponse',
  full_name='aoeinterpolator.StopPyTorchResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='aoeinterpolator.StopPyTorchResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='aoeinterpolator.StopPyTorchResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=304,
  serialized_end=359,
)

DESCRIPTOR.message_types_by_name['StartPyTorchRequest'] = _STARTPYTORCHREQUEST
DESCRIPTOR.message_types_by_name['StartPyTorchResponse'] = _STARTPYTORCHRESPONSE
DESCRIPTOR.message_types_by_name['InterpolatedFrameRequest'] = _INTERPOLATEDFRAMEREQUEST
DESCRIPTOR.message_types_by_name['InterpolatedFrameResponse'] = _INTERPOLATEDFRAMERESPONSE
DESCRIPTOR.message_types_by_name['StopPyTorchRequest'] = _STOPPYTORCHREQUEST
DESCRIPTOR.message_types_by_name['StopPyTorchResponse'] = _STOPPYTORCHRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartPyTorchRequest = _reflection.GeneratedProtocolMessageType('StartPyTorchRequest', (_message.Message,), dict(
  DESCRIPTOR = _STARTPYTORCHREQUEST,
  __module__ = 'aoe_interpolator_pb2'
  # @@protoc_insertion_point(class_scope:aoeinterpolator.StartPyTorchRequest)
  ))
_sym_db.RegisterMessage(StartPyTorchRequest)

StartPyTorchResponse = _reflection.GeneratedProtocolMessageType('StartPyTorchResponse', (_message.Message,), dict(
  DESCRIPTOR = _STARTPYTORCHRESPONSE,
  __module__ = 'aoe_interpolator_pb2'
  # @@protoc_insertion_point(class_scope:aoeinterpolator.StartPyTorchResponse)
  ))
_sym_db.RegisterMessage(StartPyTorchResponse)

InterpolatedFrameRequest = _reflection.GeneratedProtocolMessageType('InterpolatedFrameRequest', (_message.Message,), dict(
  DESCRIPTOR = _INTERPOLATEDFRAMEREQUEST,
  __module__ = 'aoe_interpolator_pb2'
  # @@protoc_insertion_point(class_scope:aoeinterpolator.InterpolatedFrameRequest)
  ))
_sym_db.RegisterMessage(InterpolatedFrameRequest)

InterpolatedFrameResponse = _reflection.GeneratedProtocolMessageType('InterpolatedFrameResponse', (_message.Message,), dict(
  DESCRIPTOR = _INTERPOLATEDFRAMERESPONSE,
  __module__ = 'aoe_interpolator_pb2'
  # @@protoc_insertion_point(class_scope:aoeinterpolator.InterpolatedFrameResponse)
  ))
_sym_db.RegisterMessage(InterpolatedFrameResponse)

StopPyTorchRequest = _reflection.GeneratedProtocolMessageType('StopPyTorchRequest', (_message.Message,), dict(
  DESCRIPTOR = _STOPPYTORCHREQUEST,
  __module__ = 'aoe_interpolator_pb2'
  # @@protoc_insertion_point(class_scope:aoeinterpolator.StopPyTorchRequest)
  ))
_sym_db.RegisterMessage(StopPyTorchRequest)

StopPyTorchResponse = _reflection.GeneratedProtocolMessageType('StopPyTorchResponse', (_message.Message,), dict(
  DESCRIPTOR = _STOPPYTORCHRESPONSE,
  __module__ = 'aoe_interpolator_pb2'
  # @@protoc_insertion_point(class_scope:aoeinterpolator.StopPyTorchResponse)
  ))
_sym_db.RegisterMessage(StopPyTorchResponse)



_AOEINTERPOLATOR = _descriptor.ServiceDescriptor(
  name='AoeInterpolator',
  full_name='aoeinterpolator.AoeInterpolator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=362,
  serialized_end=679,
  methods=[
  _descriptor.MethodDescriptor(
    name='StartPyTorch',
    full_name='aoeinterpolator.AoeInterpolator.StartPyTorch',
    index=0,
    containing_service=None,
    input_type=_STARTPYTORCHREQUEST,
    output_type=_STARTPYTORCHRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetInterpolatedFrame',
    full_name='aoeinterpolator.AoeInterpolator.GetInterpolatedFrame',
    index=1,
    containing_service=None,
    input_type=_INTERPOLATEDFRAMEREQUEST,
    output_type=_INTERPOLATEDFRAMERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StopPyTorch',
    full_name='aoeinterpolator.AoeInterpolator.StopPyTorch',
    index=2,
    containing_service=None,
    input_type=_STOPPYTORCHREQUEST,
    output_type=_STOPPYTORCHRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AOEINTERPOLATOR)

DESCRIPTOR.services_by_name['AoeInterpolator'] = _AOEINTERPOLATOR

# @@protoc_insertion_point(module_scope)
